name: motoko-classes
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-classes-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Classes Darwin
        run: |
          dfx start --background
          pushd motoko/classes
          make test
          popd
  motoko-classes-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Classes Linux
        run: |
          dfx start --background
          pushd motoko/classes
          make test
          popd
