name: motoko-actor-reference
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-actor-reference-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Actor Referenc Darwin
        run: |
          dfx start --background
          pushd motoko/actor_reference
          make test
          popd
  motoko-actor-reference-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Actor Reference Linux
        run: |
          dfx start --background
          pushd motoko/actor_reference
          make test
          popd
