name: motoko-ledger-transfer
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-ledger-transfer-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Ledger Transfer Darwin
        run: |
          pushd motoko/ledger-transfer
          bash ./demo.sh
          popd
  motoko-ledger-transfer-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Ledger Transfer Linux
        run: |
          pushd motoko/ledger-transfer
          bash ./demo.sh
          popd
