name: rust-threshold-ecdsa
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rust-threshold-ecdsa-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust Threshold ECDSA Darwin
        run: |
          dfx start --background
          pushd rust/threshold-ecdsa
          dfx deploy
          npm install
          sleep 10
          bash test.sh hello
  rust-threshold-ecdsa-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust Threshold ECDSA Linux
        run: |
          dfx start --background
          pushd rust/threshold-ecdsa
          dfx deploy
          npm install
          sleep 10
          bash test.sh hello
