name: rust-basic-dao
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rust-dao-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust DAO Darwin
        run: |
          dfx start --background
          pushd rust/basic_dao
          dfx canister create basic_dao
          dfx build
          (for f in tests/*.test.sh; do
            echo "==== Run test $f ===="
            ic-repl -r http://localhost:8000 "$f" || exit
          done)
          popd
  rust-hello-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust DAO Linux
        run: |
          dfx start --background
          pushd rust/basic_dao
          dfx canister create basic_dao
          dfx build
          (for f in tests/*.test.sh; do
            echo "==== Run test $f ===="
            ic-repl -r http://localhost:8000 "$f" || exit
          done)
          popd
